config/routes.rb
Rails.application.routes.draw do


  root to: 'pages#home'

  mount Attachinary::Engine => "/attachinary"

  devise_for :users,
  controllers: {  registrations: "registrations",
                  omniauth_callbacks: 'users/omniauth_callbacks'
                }

  resources :users, only: [:show]

  resources :meals do
    resources :orders, only: [:new, :create]
    resources :reviews, only: [:create]
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  resources :notifications, only: [:show, :index]

  resources :conversations, only: [:create] do
    resources :messages, only: [:create]
  end


  resources :conversations, only: [:create] do
    member do
      post :close
    end
  end


  get "/conversations", to: "pages#index"
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :topic, polymorphic: true
  belongs_to :order

  def mark_as_read
    self.read = true
    self.save
  end

  def self.unread(user)
    where(read: false, user: user)
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def show
    @notification = Notification.find(params[:id])
    @notification.mark_as_read
  end


  def index
    @notifications = Notification.all
  end

end

app/views/notifications/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-10 col-md-offset-1 padded">
       <% @notifications.each do | notification | %>
       <%if  notification.user_id == current_user.id %>
        <div class="notification-list">
          <div class="row">
            <div class="col-xs-3">
              <% if notification.order.user.avatar.present? %>
              <%= cl_image_tag notification.order.user.avatar.path,
                  transformation:[{ :width=>400, :height=>400, :gravity=>"face",
                  :radius=>"max", :crop=>"crop"}], class: "avatar" %>
              <% else %>
                <% avatar_url = (notification.order.user.facebook_picture_url || "http://placehold.it/30x30") %>
                <%= image_tag avatar_url, class: "avatar-reviews" %>
              <% end %>
              <br><br>
              <small><%= notification.order.user.full_name %></small>
            </div>
            <div class="col-xs-6">
              <h3><%= notification.order.quantity %> x <%= notification.order.meal.menu_name %></h3>
              <%= notification.order.meal.availability.strftime("%d/%m/%Y") %>
            </div>
            <div class="col-xs-3">
              <%= link_to "voir",notification_path(notification), class: "btn btn-warning"   %>
              </div>
          </div>
        </div>
        <% end %>
     <% end %>
   </div>

  </div>
</div>

app/views/notifications/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-10 col-md-offset-1 padded">
      <div class="row">
        <div class="notification">
          <h1>Commande de <%= @notification.order.user.full_name %></h1>
            <% if @notification.user_id == current_user.id %>

            <h3><%= @notification.order.quantity %> x <%= @notification.order.meal.menu_name %></h3>
            <h3><span> <%= "#{@notification.order.quantity * @notification.order.meal.price}" %>€</span></h3>
            <p> <strong>A préparer pour le:</strong> <%= @notification.order.meal.availability.strftime("%d/%m/%Y") %></p>

            <h4>Message de <%= @notification.order.user.first_name %></h4>
            <p><%= @notification.order.message %></p>

            <%= link_to "Retour aux notifications", notifications_path, class: "btn btn-warning btn-lg"  %>
            <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>