config/routes.rb
Rails.application.routes.draw do


  root to: 'pages#home'

  mount Attachinary::Engine => "/attachinary"

  devise_for :users,
  controllers: {  registrations: "registrations",
                  omniauth_callbacks: 'users/omniauth_callbacks'
                }

  resources :users, only: [:show]

  resources :meals do
    resources :orders, only: [:new, :create]
    resources :reviews, only: [:create]
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  resources :notifications, only: [:show, :index]

  resources :conversations, only: [:create] do
    resources :messages, only: [:create]
  end


  resources :conversations, only: [:create] do
    member do
      post :close
    end
  end


  get "/conversations", to: "pages#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #devise :omniauthable, omniauth_providers: [:facebook]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]


  has_many :messages, dependent: :destroy
  has_many :conversations, foreign_key: :sender_id

  has_many :meals, dependent: :destroy #Meals that the user offers

  has_many :received_orders, class_name: "Order"
  has_many :prepared_orders, through: :received_orders,  class_name: "Meal", source: :meal

  has_many :orders, dependent: :destroy#User palce an order

  has_many :reviews, through: :meals,dependent: :destroy
  has_many :notifications, dependent: :destroy



  has_attachment :avatar


  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  def update_with_password(params={})
    params.delete(:current_password)
    self.update_without_password(params)
  end

  def signed_without_oauth?
    provider != "facebook"
  end

  def completed_profile?
   if first_name.present? && last_name.present? && nickname.present?
     true
   else
    false
   end
  end

  def received_reviews
    reviews = []
    meals.each do |meal|
     meal.reviews.each do |review|
      reviews << review
    end
   end
    reviews.size
  end

  def buyer
  end
  def rating_average
    sum = 0
    meals.each do |meal|
      meal.reviews.each do |review|
        sum += review.rating.to_i
      end
    end
    average = sum / reviews.count
    return average
  end

  def full_name
   "#{self.first_name} #{self.last_name}"
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end
  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :nickname, :avatar, :email, :password, :password_confirmtaion, :current_password)
  end
end

app/views/users/_awaiting-meal-ordered.html.erb
<!-- Repas commandé par le user, en attente -->
  <div class="tab-content hidden" id="awaiting-meal-ordered">
    <% if @user.placed_orders.present? %>
        <div class="col-md-8 col-md-offset-2 ">
      <% @user.placed_orders.coming.each do|meal| %>
        <%= link_to meal_path(meal) do  %>

        <%= render "shared/meal_card", meal: meal %>

        <% end %>

      <% end %>
    <% end %>
  </div>

app/views/users/_awaiting-meal.html.erb
  <div class="tab-content hidden" id="awaiting-meal">
    <% if @user.placed_orders.present? %>
        <div class="col-md-8 col-md-offset-2 ">
      <% @user.placed_orders.coming.each do|meal| %>
        <%= link_to meal_path(meal) do  %>

        <%= render "shared/meal_card", meal: meal %>

        <% end %>

      <% end %>
    <% end %>
  </div>

app/views/users/_next-meal-order.html.erb
  <div class="tab-content hidden" id="next-meal-order">
    <% @user.meals.each do |meal| %>

      <div class="col-md-8 col-md-offset-2">
        <% if !meal.passed? %>
          <%= link_to meal_path(meal) do  %>

            <%= render "shared/meal_card", meal: meal %>

          <% end %>
        <% end %>
      </div>

    <% end %>
  </div>

app/views/users/_old-meal-order.html.erb
  <div class="tab-content hidden" id="old-meal-order">
    <% @user.meals.each do |meal| %>

        <% if meal.passed? %>
        <div class="col-md-8 col-md-offset-2">
          <%= link_to meal_path(meal) do  %>

            <%= render "shared/meal_card", meal: meal %>

          <% end %>
        </div>
        <% end %>

    <% end %>
  </div>

app/views/users/_old-proposed-meal.html.erb
<!-- Repas que le user proposait (passé) -->
  <div class="tab-content hidden" id="old-meal-proposed">
    <% @user.meals.each do |meal| %>
        <% if meal.passed? %>
        <div class="col-md-8 col-md-offset-2">
          <%= link_to meal_path(meal) do  %>

            <%= render "shared/meal_card", meal: meal %>

          <% end %>
        </div>
        <% end %>
    <% end %>
  </div>

app/views/users/_proposed-meal.html.erb
  <!-- repas que le user propose (en ce moment) -->
  <div class="tab-content hidden" id="next-meal-proposed">
    <% @user.meals.each do |meal| %>
      <div class="col-md-8 col-md-offset-2">
        <% if !meal.passed? %>
          <%= link_to meal_path(meal) do  %>

            <%= render "shared/meal_card", meal: meal %>

          <% end %>
        <% end %>
      </div>

    <% end %>
  </div>

app/views/users/_review.html.erb
<div class="col-xs-10 col-xs-offset-1" id="reviews">
  <div class="reviews-content">
    <div class="average text-center">
      <% if @user.received_reviews > 0 %>
        <h3>Note moyenne</h3>
        <div class="review-rating" data-score="<%= @user.rating_average %>"></div>
        <hr>
        <% else %>
        <% if current_user.id == @user.id %>
          <h4>Tu n'as pas encore d'avis</h4>
          <%= link_to "Propose", new_meal_path, class: "btn btn-lg btn-warning" %>
        <% else %>
          <h3><%= @user.first_name %> n'a pas encore de review</h3>
        <% end %>
      <% end %>
    </div>
    <% @user.meals.each do | meal|%>
      <%  meal.reviews.each do |review|%>
      <div class="row">
        <div class="review-block">
          <div class="col-xs-12">
            <div class="col-xs-2">
              <div class="user-side">
                <!-- user pic and name -->
                <% if review.user.avatar.present? %>
                <%= cl_image_tag review.user.avatar.path, :transformation=>[
                {:width=>400, :height=>400, :gravity=>"face", :radius=>"max", :crop=>"crop"},
                {:width=>40, :height=>40, :crop=>"scale"}
                ], class: "avatar" %>
                <% else %>
                  <% avatar_url = (review.user.facebook_picture_url || "http://placehold.it/30x30") %>
                  <%= image_tag avatar_url, class: "avatar-reviews" %>
                <% end %>
                 <h4> <%= review.user.first_name %></h4>
              </div>
            </div>
            <div class="col-xs-10">
              <div class="user-review-rating">
                <div class="review-rating" data-score="<%= review.rating %>"></div>
                <h4><%= meal.menu_name %>:</h4>
                <p><%= review.comment %></p>
              </div>
            </div>

          </div>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/_reviews.html.erb
<div class="tab-content hidden" id="reviews">

  <% @user.meals.each do | meal|%>
    <%  meal.reviews.each do |review|%>
      <div class="card-review">
        <div class="review-user-info">
          <div class="review-user-avatar">
            <% if review.user.avatar.present? %>
              <%= cl_image_tag review.user.avatar.path, :transformation=>[
              {:width=>400, :height=>400, :gravity=>"face", :radius=>"max", :crop=>"crop"},
              {:width=>50, :height=>50, :crop=>"scale"}
              ], class: "avatar-reviews" %>
            <% else %>
              <% avatar_url = (review.user.facebook_picture_url || "http://placehold.it/30x30") %>
              <%= image_tag avatar_url, class: "avatar-reviews" %>
            <% end %>
          </div>
          <div class="review-user-name">
            <h3> <%= review.user.first_name %> </h3>
          </div>
        </div>
        <div class="review-body">
            <h4><%= meal.menu_name %>:</h4>
            <% review.rating.times do %>
              <i class="fa fa-star" aria-hidden="true"></i>
            <% end %>
             <p><%= review.comment %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="row padded">
  <div class="col-md-8">
    <div class="col-xs-12 col-md-10 col-md-offset-1">
        <div class="tabs">
          <a class="tab active" data-target="#next_meal_proposed">
            <h4>Les Miams proposés</h4>
          </a>
          <a class="tab" data-target="#awaiting_meal_ordered">
            <h4>Les Miams commandés</h4>
          </a>
        </div>
        <div class="tabs">
          <a class="tab" data-target="#old_meal_proposed">
            <h4>Les Miams passés</h4>
          </a>
          <a class="tab" data-target="#old_meal_ordered">
            <h4>Les Miams dégustés</h4>
          </a>
        </div>
      <div class="incoming">
        <%= render partial: "users/ongoing/proposed_meal" %>
        <%= render partial: "users/ongoing/awaiting_meal_ordered" %>
      </div>
    </div>
    <div class="col-xs-12 col-md-10 col-md-offset-1">
      <div class="passed">
          <%= render partial: "users/passed/old_proposed_meal" %>
          <%= render partial: "users/passed/old_meal_ordered" %>
      </div>
    </div>

  </div>
  <div class="col-md-4">
    <%= render partial: "users/review" %>
  </div>
</div>