config/routes.rb
Rails.application.routes.draw do


  root to: 'pages#home'

  mount Attachinary::Engine => "/attachinary"

  devise_for :users,
  controllers: {  registrations: "registrations",
                  omniauth_callbacks: 'users/omniauth_callbacks'
                }

  resources :users, only: [:show]

  resources :meals do
    resources :orders, only: [:new, :create]
    resources :reviews, only: [:create]
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  resources :notifications, only: [:show, :index]

  resources :conversations, only: [:create] do
    resources :messages, only: [:create]
  end


  resources :conversations, only: [:create] do
    member do
      post :close
    end
  end


  get "/conversations", to: "pages#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_landing_nav.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to "Miam", root_path, class: "navbar-wagon-brand" %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>


      <%= link_to "Proposer", new_meal_path, class: "btn btn-lg btn-warning" %>


          <!-- notification commande -->
        <div class="navbar-wagon-item">
          <div class="dropdown">
            <div class="badge-container dropdown-toggle", data-toggle="dropdown">
              <i class="fa fa-envelope-o" aria-hidden="true" style="color: #fff"></i>
              <div class="badge badge-blue"><%= Notification.unread(current_user).count %></div>
            </div>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <% Notification.unread(current_user).each do |notification| %>


                <li><%= link_to notification_path(notification) do %>
                  <%= notification.content %>
                <% end %></li>




              <% end %>
            </ul>
          </div>
        </div>


      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
        <% if current_user.avatar.present? %>
          <%= cl_image_tag current_user.avatar.path, :transformation=>[
          {:width=>400, :height=>400, :gravity=>"face", :radius=>"max", :crop=>"crop"},
          {:width=>40, :height=>40, :crop=>"scale"}
          ], class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% else %>
          <% avatar_url = (current_user.facebook_picture_url || "http://placehold.it/30x30") %>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to user_path(current_user)  do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to  edit_user_registration_path  do %>
                <i class="fa fa-wrench"></i>  <%=  "Edit" %>
              <% end %>
            </li>
            <li>
              <%= link_to  conversations_path  do %>
                <i class="fa fa-wechat"></i>  <%=  "Chat" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <% end %>

  </div>

  <% if user_signed_in? %>
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to root_path do %>
              <i class="fa fa-home"></i>
              <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
        <li>
          <%= link_to user_path(current_user)  do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <li>
         <%= link_to  edit_user_registration_path  do %>
           <i class="fa fa-wrench"></i>  <%=  "Edit" %>
         <% end %>
       </li>
       <li>
         <%= link_to destroy_user_session_path, method: :delete do %>
           <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
         <% end %>
       </li>
      </ul>
    </div>
  </div>



  <% end %>
  <!-- Dropdown list appearing on mobile only -->
</div>

app/views/shared/_meal_card.html.erb
  <div class="product">

    <div class='product-upvote'>
      <h4><%= meal.menu_name %></h4>
      <p><%= humanized_money(meal.price) %>€</p>

    </div>

    <div class="product-image">
      <% if  meal.images?%>
       <%= cl_image_tag meal.images.first.path, :transformation=>[
       {:width=>150, :height=>75, :crop=>"fill"}],class:"hidden-xs"%>
      <% end %>
      <small><%= meal.category.name %></small>
  </div>

    <div class='product-body'>
      <h3><%= meal.availability.strftime("%d/%m/%Y")%></h3>
      <p><%= meal.location %></p>
    </div>

    <div class="product-info">
      <% if meal.user.avatar.present? %>
        <%= cl_image_tag meal.user.avatar.path, :transformation=>[
        {:width=>400, :height=>400, :gravity=>"face", :radius=>"max", :crop=>"crop"},
        {:width=>50, :height=>50, :crop=>"scale"}
        ], class: "avatar-large" %>
      <% else %>
        <% avatar_url = (meal.user.facebook_picture_url || "http://placehold.it/30x30") %>
        <%= image_tag avatar_url, class: "avatar-large" %>
      <% end %>
      <p><i class="fa fa-cutlery" aria-hidden="true"></i> <strong><%= meal.user.nickname  %></strong></p>
    </div>


  </div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to "Miam", root_path, class: "navbar-wagon-brand" %>

  <div class="hidden-xs nav-search">
    <%= simple_form_for :query, url: meals_path, method: :get, wrapper: :inline_form, html: {class:"form-inline"} do |f| %>
      <%= f.input :location, placeholder: "Entrez une ville", input_html: {class: 'autocomplete form_input_home' }%>
      <%= f.button :submit, "Trouver", class: "btn btn-lg btn-warning" %>
    <% end %>
  </div>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>


      <%= link_to "Proposer", new_meal_path, class: "btn btn-lg btn-warning", id: "btn-propose" %>


        <!-- notification commande -->
        <div class="navbar-wagon-item">
          <div class="dropdown">
            <div class="badge-container dropdown-toggle", data-toggle="dropdown">
              <i class="fa fa-envelope-o" aria-hidden="true" style="color: $orange"></i>
              <div class="badge badge-blue"><%= Notification.unread(current_user).count %></div>
            </div>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <% Notification.unread(current_user).each do |notification| %>


                <li><%= link_to notification_path(notification) do %>
                  <%= notification.content %>
                <% end %></li>


              <% end %>
            </ul>
          </div>
        </div>


      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
        <% if current_user.avatar.present? %>
          <%= cl_image_tag current_user.avatar.path, :transformation=>[
          {:width=>400, :height=>400, :gravity=>"face", :radius=>"max", :crop=>"crop"},
          {:width=>40, :height=>40, :crop=>"scale"}
          ], class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% else %>
          <% avatar_url = (current_user.facebook_picture_url || "http://placehold.it/30x30") %>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to user_path(current_user)  do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to  edit_user_registration_path  do %>
                <i class="fa fa-wrench"></i>  <%=  "Edit" %>
              <% end %>
            </li>
            <li>
              <%= link_to  conversations_path  do %>
                <i class="fa fa-wechat"></i>  <%=  "Chat" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

      <% end %>

  </div>

  <% if user_signed_in? %>
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to root_path do %>
              <i class="fa fa-home"></i>
              <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
        <li>
          <%= link_to user_path(current_user)  do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <li>
         <%= link_to  edit_user_registration_path  do %>
           <i class="fa fa-wrench"></i>  <%=  "Edit" %>
         <% end %>
       </li>
       <li>
         <%= link_to destroy_user_session_path, method: :delete do %>
           <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
         <% end %>
       </li>
      </ul>
    </div>
  </div>
  <% else %>
  <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

  <% end %>


  <!-- Dropdown list appearing on mobile only -->
</div>

app/views/shared/_search_location.html.erb
<div class="row padded">

<h1><strong>Vos voisins peuvent remplir votre assiette</strong></h1>
<%= simple_form_for :query, url: meals_path, method: :get, wrapper: :inline_form do |f| %>
  <div class="col-xs-12 col-md-8 col-md-offset-2">
    <div class="col-xs-12 col-md-9">
    <%= f.input :location, placeholder: "Chercher un repas", input_html: {class: 'autocomplete form_input_home' }%>
    </div>
     <div class="col-xs-12 col-md-3">
    <%= f.button :submit, "Trouver", class: "btn btn-lg btn-warning" %>
     </div>
  </div>

<% end %>
</div>