config/routes.rb
Rails.application.routes.draw do


  root to: 'pages#home'

  mount Attachinary::Engine => "/attachinary"

  devise_for :users,
  controllers: {  registrations: "registrations",
                  omniauth_callbacks: 'users/omniauth_callbacks'
                }

  resources :users, only: [:show]

  resources :meals do
    resources :orders, only: [:new, :create]
    resources :reviews, only: [:create]
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  resources :notifications, only: [:show, :index]

  resources :conversations, only: [:create] do
    resources :messages, only: [:create]
  end


  resources :conversations, only: [:create] do
    member do
      post :close
    end
  end


  get "/conversations", to: "pages#index"
end

app/models/meal.rb
class Meal < ApplicationRecord
  has_attachments :images, maximum: 3

  belongs_to :category
  belongs_to :user

  has_many :ingredients
  has_many :orders, dependent: :destroy
  has_many :notifications, as: :topic
  has_many :reviews

  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true

  geocoded_by :location

  after_validation :geocode, if: :location_changed?
  validates :menu_name, :price, :portion, :availability, :location , :category, presence: true


  def coming?
    true if  self.availability >=  Date.current
  end

  def passed?
     true if  self.availability <  Date.current
  end

  def left_meal
   meals = 0
    orders.each do |order|
      meals += order.quantity if order.payment_status?
    end
    left_meal = self.portion - meals
    return left_meal.to_i
  end

  def self.search(search)
    if search
     where(["lower(location) LIKE ?","%#{search.downcase}%"]).order('created_at DESC')
    else
      all
    end
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

  before_action :find_meal, only: [:show, :update, :edit, :destroy]


  def index
    #filter_by_location if params[:query].present?
    meal_filter = MealsFilter.new(params)
    @meals = meal_filter.filter
    @meals_count = @meals.count
    #add_markers_on_map
    @categories = Category.all
  end

  def show
    @order = Order.new
    @review = Review.new
    @user = @meal.user
  end

  def new
   if current_user.completed_profile?
     @meal = Meal.new
   else
     redirect_to edit_user_registration_path, alert: 'Merci de compléter votre profile'
   end
  end

  def create
    @meal = Meal.new(meal_params)
    @meal.user = current_user
    respond_to do |format|
      if @meal.save
        format.html { redirect_to @meal, notice: 'Repas créé avec succès!' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @meal.destroy
  end

  def update
    if @meal.update(meal_params)
      redirect_to meal_path(@meal)
    else
      render :edit
    end
  end

  def edit
  end

  private

  def find_meal
    @meal = Meal.find(params[:id])
  end

  def meal_params
    params.require(:meal)
    .permit(:menu_name,
            :price,
            :portion,
            :availability,
            :category_id,
            :location,
            images: [],
            ingredients_attributes: [:id, :name, :_destroy])
  end


  def filter_by_location
    @meals = Meal.search(params[:query][:location]) if params[:query][:location].present?
  end

  # def filter_by_category
  #  if params[:categories] != nil && params[:categories].size != 0 && !params[:categories].include?("all")
  #    @meals = @meals.joins(:category).where("categories.name IN (?)", params[:categories])
  #  end
  # end

  def add_markers_on_map
    @meals_location = @meals.where.not(latitude: nil, longitude: nil)
    @markers_hash = Gmaps4rails.build_markers(@meals_location) do |meal, marker|
        marker.lat meal.latitude
        marker.lng meal.longitude
        marker.json({ :id => meal.id })
        marker.infowindow render_to_string(partial: "/meals/map_box", locals: { meal: meal })
    end
  end

end

app/views/meals/_category_filter.html.erb
<div class="col-xs-3">
  <section class="choice" id="normal-choice">
    <form action="/meals" method="get" class= "normal-form">
      <ul class="list-unstyled">
        <label class="categories">
        <% @categories.each do |category| %>
          <li>
            <label class="categories">
              <input type="checkbox" name="categories[]" value="<%= category.name %>"
                <%= "checked" if !params[:categories].nil? && params[:categories].include?(category.name) %>>

              <span>
                 <span class="icons text-center">
                    <!-- <i class="fa fa-star aria-hidden="true"></i> -->
                 </span>
                <%= category.name %>
              </span>


            </label>
          </li>
        <% end %>
          <%= link_to 'Effacer les filtres', meals_path('category[]' => 'all') %>

        </label>
      </ul>
      <input class="valid-btn" type="submit" value="Filtrer">
    </form>
  </section>

</div>

app/views/meals/_form.html.erb
<div class="container">
  <div class="row padded">

    <div class="meal-form">
      <%= simple_form_for @meal do |f| %>
      <div class="col-xs-12 col-md-8 col-md-offset-2">
          <h2>Crée le miam que tu veux partager</h2>

        <div class="row">
          <div class="col-xs-7">
            <%= f.input :menu_name, placeholder: "Le nom de ton repas", label: false,  input_html: {class: 'form_input_meal' } %>
          </div>

          <div class="col-xs-4 col-xs-offset-1 meal-category">
            <%= f.collection_select :category_id, Category.all, :id, :name, { include_blank: "Séléctionnez une catégorie"  }%>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-12">
            <h4>Précise un maximm d'ingrédients:</h4>

            <div id="ingredients" class="ingredients">
              <%= f.simple_fields_for :ingredients do |ingredient| %>
                <%= render "ingredients_fields", f: ingredient %>
              <% end %>
              <div class="links">
                <%= link_to_add_association "Ajouter un ingrédient", f, :ingredients, partial: "ingredients_fields", class:"btn btn-warning btn-sm" %>
              </div>
            </div>

          </div>
        </div>

       <div class="row">
         <div class="col-xs-4">
           <%= f.input :portion, label: false, placeholder: "Nombre de parts", input_html: {class: 'form_input_meal' } %>
         </div>

         <div class="col-xs-4 meal-date">
           <%= f.input :availability,  input_html: {class: 'form_input_meal' }%>
         </div>
          <div class="col-xs-4">
            <%= f.input :price, label: false, placeholder: "Prix/part", input_html: {class: 'form_input_meal' } %>
          </div>
       </div>

        <div class="row">
            <div class="col-xs-3">
              <div class="uploader">
                <%= f.input :images, as: :attachinary , label: false ,required: true %>
              </div>
            </div>

          <div class="col-xs-12">
            <%= f.input :location , label: false, placeholder:  "Où venir chercher", input_html: {class: 'form_input_meal' }%>
          </div>
        </div>
      </div>

      <div class="col-xs-12  col-md-10 col-md-offset-1 text-center">
        <%= f.submit "Valider" , class:"btn btn-warning btn-lg btn-event" , title: "Valider" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/meals/_ingredients_fields.html.erb
<div class="nested-fields">
  <%= f.input :name, label: false, placeholder: "Ajouter un ingredient", input_html: {class: 'form_input_meal' } %>
  <div class="links">
    <%= link_to_remove_association "Supprimer cet ingrédient", f , class: "btn btn-danger btn-sm" %>
  </div>
</div>

app/views/meals/_map_box.html.erb
<h3><%= meal.menu_name %></h3>
<p>Cuisiné par: <%= meal.user.nickname %></p>
<% if meal.images? %>
  <%= cl_image_tag meal.images.first.path, width: 150, height: 100, crop: :fill %>
<% end %>
<p><%= meal.location %></p>

<p><%= link_to "En savoir plus",meal_path(meal)  %></p>

app/views/meals/_order_form.html.erb
<div class="col-xs-12 padded">
  <%= simple_form_for [ @meal, @order] do |f| %>
    <div class="col-xs-2">
      <%= f.input :quantity, label: "Parts", collection: (1..@meal.left_meal) %>
    </div>
    <div class="col-xs-12">
      <%= f.input :message %>
      <%= f.submit :Valider, class:"btn btn-warning"%>
    </div>
  <% end %>
</div>

app/views/meals/_review.html.erb
  <div class="review padded">
    <div class="col-xs-8 col-xs-offset-2">
      <% @meal.reviews.each do |review| %>
        <p><strong><%= review.user.nickname %></strong></p>

        <div class="review-rating" data-score="<%= review.rating %>"></div>

        <p><%= review.comment %></p>
        <hr>
      <% end %>
    </div>
  </div>

app/views/meals/_review_form.html.erb
  <%= simple_form_for [@meal, @review] do |f| %>
    <div id="rating-form">
      <label>Rating</label>
    </div>
    <%= f.input :comment,  input_html: { type: "text"} %>
    <%= f.submit  %>
  <% end %>

app/views/meals/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <%= render "form" %>

    </div>
  </div>
</div>

app/views/meals/index.html.erb
<div class="container">
  <div class="row">
  <%#= render 'shared/search_location' %>
  <%= render 'category_filter' %>
  <div class="col-xs-9">
    <section class="meals-normal">
      <% if @meals_count != 0 %>
        <div class="row">
          <% @meals.sort.each do |meal| %>
            <% unless meal.passed?  %>
            <%= link_to meal_path(meal) do  %>

              <%= render "shared/meal_card", meal: meal %>

            <% end %>
            <% end %>
          <% end %>
        </div>
      <% else %>
        <p class="no-meal">Aucun repas ne correspond à votre recherche.

         <%= link_to 'Effacer les filtres', meals_path('category[]' => 'all') %>
         </p>
      <% end %>

    </section>
  </div>

  </div>
<!--     <div id="map" style="width: 100%; height: 600px;" data-markers='<%#= raw @markers_hash.to_json %>'></div>
 -->

</div>

app/views/meals/new.html.erb
<div class="container">
  <div class="row">

      <%= render "form" %>


  </div>
</div>

app/views/meals/show.html.erb
<div class="container">
  <div class="col-md-10 col-md-offset-1">
      <h1 class="menu-title"><%= @meal.menu_name %>
        <% if current_user.id == @meal.user.id %>
          <%= link_to  "Edit", edit_meal_path(@meal), class: "btn btn-warning"  %>
        <% end %></h1>

        <div class="row">
          <div class="col-md-12 hidden-xs">
            <div class="meals-images">
              <% @meal.images.each do |image| %>
                <%= cl_image_tag image.path, width: 300, height: 200, crop: :fill %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="meal-description">
          <div class="row">
            <div class="col-xs-12 col-sm-6">
              <h3>Proposé par <%= link_to @meal.user.nickname, user_path(id: @meal.user.id) %></h3>
               <ul class="list-unstyled">
                   <li><i class="fa fa-cutlery" aria-hidden="true"></i><%= @meal.left_meal %> part(s) disponible(s)</li>
                   <br>
                   <li><i class="fa fa-euro" aria-hidden="true"></i> <%= humanized_money(@meal.price) %> €/part</li>
                   <br>
                   <li><i class="fa fa-calendar-check-o" aria-hidden="true"></i> <%= @meal.availability.strftime("%d/%m/%Y")%></li>
               </ul>
            </div>
            <div class="col-xs-12 col-sm-6">
                <h3>Ingrédients:</h3>
                <ul>
                  <% @meal.ingredients.each do |ingredients| %>
                    <li><%= ingredients.name %></li>
                  <% end %>
                </ul>
            </div>
          </div>
        </div>


    <% unless current_user.id == @meal.user_id %>
      <div class="row">
        <div class="order">
          <div class="col-xs-8 col-xs-offset-2">
          <% if  @meal.passed?%>
            <%= render "review_form" %>
          <% else %>
            <%= render "order_form" %>
          <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <%= render "review" %>
  </div>
</div>